server:
  port: 8000
spring:
  application:
    name: service-power
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  devtools:
    restart:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'