server:
  port: 8000
  servlet:
    context-path:
spring:
  application:
    name: power
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  devtools:
    restart:
      enabled: true