package com.monk.webservice.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-05-14T14:22:31.808+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://server.qywxWSServer.haid.com.cn/", name = "sapPushWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface SapPushWebService {

    @WebMethod
    @RequestWrapper(localName = "sappushwebservice", targetNamespace = "http://server.qywxWSServer.haid.com.cn/", className = "com.haida.qywxWSServer.server.Sappushwebservice_Type")
    @ResponseWrapper(localName = "sappushwebserviceResponse", targetNamespace = "http://server.qywxWSServer.haid.com.cn/", className = "com.haida.qywxWSServer.server.SappushwebserviceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sappushwebservice(
        @WebParam(name = "pushaddress", targetNamespace = "")
        java.lang.String pushaddress,
        @WebParam(name = "touser", targetNamespace = "")
        java.lang.String touser,
        @WebParam(name = "toparty", targetNamespace = "")
        java.lang.String toparty,
        @WebParam(name = "totag", targetNamespace = "")
        java.lang.String totag,
        @WebParam(name = "msgtype", targetNamespace = "")
        java.lang.String msgtype,
        @WebParam(name = "textcontent", targetNamespace = "")
        java.lang.String textcontent,
        @WebParam(name = "textcardtitle", targetNamespace = "")
        java.lang.String textcardtitle,
        @WebParam(name = "textcarddescription", targetNamespace = "")
        java.lang.String textcarddescription,
        @WebParam(name = "textcardurl", targetNamespace = "")
        java.lang.String textcardurl,
        @WebParam(name = "textcardbtntxt", targetNamespace = "")
        java.lang.String textcardbtntxt,
        @WebParam(name = "safe", targetNamespace = "")
        java.lang.String safe
    );
}
