server:
  port: 8080
#  servlet:
#    context-path: /demo


monk:
  security:
    validateCode:
      imageCode:
        length: 6
        width: 100
        urls: /order,/user/*
      smsCode:
        urls: /order,/user/*
    browser:
#      loginPage: /cus-login.html
      registerPage: /cus-register.html
    social:
      processesUrl: /qqLogin
      qq:
        app-id:
        app-secret:
        providerId: callback.do
      wechat:
        app-id:
        app-secret:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.94.200:3306/monk_security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
