server:
  port: 8100
spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  devtools:
    restart:
      enabled: true
hystrix:
  command:
    default:
      execution:
        circuitBreaker:
          requestVolumeThreshold: 5   #限流,设置请求失败5次之后开启熔断器(默认:20)

